### ISSUE TITLE
當用bm25計算權重值時，這個值最大是多少呢？

### ISSUE THREAD

**Issue by zhenruyan** [Alex-CHUN-YU/BM25#1]

**Comment by Alex-CHUN-YU** [comment]
zhenruyan 你好:
最大值會受到資料集(Corpus) 裡的資料以及輸入的句子(query)長短影響且使用的斷詞系統也是影響的因素之一，故此值是不固定的。謝謝你的發問~
best regards,
Alex

**Comment by zhenruyan** [comment]
多謝指點
